name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: "postgres:13"
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '23.2.6'
          elixir-version: '1.11.3'
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: MIX_ENV=test mix db.reset
      - run: mix test
